# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALARM_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ALARM_ID', models.CharField(max_length=32)),
                ('ALARM_TITLE', models.CharField(max_length=512)),
                ('ALARM_TIME', models.CharField(max_length=32)),
                ('MESSAGE', models.CharField(max_length=512)),
                ('CONFIRM_TIME', models.CharField(max_length=32)),
                ('CONFIRM_USER_ID', models.CharField(max_length=32)),
                ('RESOLVE_TIME', models.CharField(max_length=32)),
                ('HOST_NAME', models.CharField(max_length=32)),
                ('RESOLVE_PERIOD', models.CharField(max_length=32)),
                ('CONFIRM_PERIOD', models.CharField(max_length=32)),
                ('SEVERITY', models.CharField(max_length=32)),
                ('ALARM_TYPE', models.CharField(max_length=32)),
                ('ALARM_STATUS', models.CharField(max_length=32)),
                ('ADDIN', models.CharField(max_length=32)),
                ('REMOVED', models.CharField(max_length=32)),
                ('REL_WECHAT', models.CharField(max_length=32)),
                ('HOST_GROUP', models.CharField(max_length=32)),
                ('COMPRESSED_BY_TIME', models.CharField(max_length=32)),
                ('COMPRESSED_BY_KEYWORD', models.CharField(max_length=32)),
                ('COMPRESSED_BY_HOST', models.CharField(max_length=32)),
            ],
        ),
    ]
