# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_wechat_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DUTY_ROSTER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NICK_NAME', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TOKEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIME', models.CharField(max_length=32)),
                ('TOKEN', models.CharField(max_length=64)),
            ],
        ),
    ]
