# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_wechat_db', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEMP_CLOSED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BEGINTIME', models.CharField(max_length=32)),
                ('ENDTIME', models.CharField(max_length=32)),
                ('HOST_NAME', models.CharField(max_length=32)),
                ('HOST_GROUP', models.CharField(max_length=32)),
                ('ALARM_TITLE', models.CharField(max_length=512)),
                ('REMOVED', models.CharField(max_length=32)),
                ('USER_ID', models.CharField(max_length=32)),
            ],
        ),
    ]
