# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_wechat_db', '0004_temp_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='AGENTID',
            field=models.CharField(default='', max_length=64),
        ),
    ]
