# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_wechat_db', '0005_group_agentid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TOKEN',
        ),
    ]
