# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_wechat_db', '0006_delete_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALARM_DEPEND',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ALARM_TITLE', models.CharField(max_length=32)),
                ('ALARM_DEPEND_TIELE', models.CharField(max_length=32)),
            ],
        ),
    ]
