# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_wechat_db', '0007_alarm_depend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm_depend',
            old_name='ALARM_DEPEND_TIELE',
            new_name='ALARM_DEPEND_TITLE',
        ),
    ]
